version: '3.2'

services:

  radsecproxy:
    network_mode: host
    build:
      dockerfile: DockerfileRadSecProxy
      context: .
    volumes:
      - "./configs/radsecproxy/radsecproxy.conf:/etc/radsecproxy.conf"
      - "./configs/radsecproxy/certs:/etc/radsecproxy/certs"

    environment:
      - RUN_IN_BACKGROUND=false
    restart: always
